services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0              # Forward host display
    volumes:
      - .:/home/cs2620/wire-protocols               # Mount the project directory
    stdin_open: true
    tty: true