services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0              # Forward host display
    volumes:
      - .:/home/cs2620/wire-protocols               # Mount the project directory
      - /tmp/.X11-unix:/tmp/.X11-unix
    extra_hosts:
      - "host.docker.internal:host-gateway"         # Add host.docker.internal to /etc/hosts
    stdin_open: true
    tty: true