services:
  app:
    build: .
    network_mode: "host"                            # Gives access to host's network, including lo interface
    cap_add:
      - NET_ADMIN                                   # Required for Wireshark
      - NET_RAW
    security_opt:
      - seccomp:unconfined                          # Disable seccomp for Wireshark
    environment:
      - DISPLAY=host.docker.internal:0              # Forward host display
    volumes:
      - .:/home/cs2620/wire-protocols               # Mount the project directory
      - /tmp/.X11-unix:/tmp/.X11-unix
    extra_hosts:
      - "host.docker.internal:host-gateway"         # Add host.docker.internal to /etc/hosts
    stdin_open: true
    tty: true