load_balancer:

replica:
    - name: replica_1
      port: 12345
      db: "replica_db/replica_1"
    - name: replica_2
      port: 12346
      db: "replica_db/replica_2"
    - name: replica_3
      port: 12347
      db: "replica_db/replica_3"

topology:
  - ["replica_1", "replica_2"]
  - ["replica_2", "replica_3"]
  - ["replica_1", "replica_3"]