service SocketOut {
    rpc register_user(RegisterRequest) returns (RegisterResponse) {}

    rpc login(LoginRequest) returns (stream LoginResponse) {}

    rpc create_channel(CreateChannelRequest) returns (CreateChannelResponse) {}

    rpc send_message(SendMessageRequest) returns (SendMessageResponse) {}

    rpc delete_message(DeleteMessageRequest) returns (DeleteMessageResponse) {}

    rpc delete_account(DeleteAccountRequest) returns (DeleteAccountResponse) {}

    rpc list_accounts(ListAccountsRequest) returns (stream ListAccountResponse) {}
}

message RegisterRequest {
    required string username = 1;
    required string password = 2;
}

message RegisterResponse {
    required string data = 1;
}

message LoginRequest {
    required string username = 1;
    required string password = 2;
}

message LoginResponse {
    required string data = 1;
}

message CreateChannelRequest {
    required string channel_name = 1;
}

message CreateChannelResponse {
    required string data = 1;
}

message SendMessageRequest {
    required string channel_name = 1;
    required string data = 2;
}

message SendMessageResponse {
    required string data = 1;
}

message DeleteMessageRequest {
    required string channel_name = 1;
    required int32 message_id = 2;
}

message DeleteMessageResponse {
    required string data = 1;
}

message DeleteAccountRequest {
    required string username = 1;
    required string password = 2;
}

message DeleteAccountResponse {
    required string data = 1;
}

message ListAccountsRequest {
    required string username = 1;
    required string password = 2;
}

message ListAccountResponse {
    required string username = 1;
    required string password = 2;
}